### ISSUE TITLE
How to Create Local Composer Mirror

### ISSUE THREAD

**Issue by cs16lover** [zencodex/composer#1]
Hello,
 
I'm a student in a university.
 
I found your project: https://laravel-china.org/composer
 
It looks very good. First of all thank you for such a good project +1
 
I would like to ask how can I create my offline composer repository like you did?
 
Can you share source codes and instructions so I can install locally in my university?
 
Please help me.
 
Thanks

**Comment by zencodex** [comment]
1. toran: https://toranproxy.com/,  same author of composer.
But Toran Proxy is being phased out. Try [Private Packagist](https://packagist.com/) instead!

2. satis
Simple static Composer repository generator.
