### ISSUE TITLE
composer 用户验真

### ISSUE THREAD

**Issue by Banweijun** [zencodex/composer#12]
Downloading https://packagist.phpcomposer.com/p/guzzlehttp/promises%24536732058f09b3f2c662001a799d679e3c29e720144be868448b65f4efabb70f.json

    Authentication required (packagist.phpcomposer.com):
      Username:

composer.json

¦12¦: {
    ¦   ¦   ¦type¦: ¦composer¦,
    ¦   ¦   ¦url¦: ¦https://packagist.phpcomposer.com
    ¦   },
    ¦   ¦packagist: {
    ¦   ¦   ¦type¦: ¦composer¦,
    ¦   ¦   ¦url¦: ¦ https://packagist.laravel-china.org
    ¦   }
    }

换了源 还是这样 ， 帮忙看下 谢谢

**Comment by zencodex** [comment]
正常没有需要授权的地方，不太清楚你这个提示是指哪个，使用代理上网的 授权提示？
