### ISSUE TITLE
Homestead 中 composer 安装 laravel 报错！ 

### ISSUE THREAD

**Issue by tuntunBtc** [zencodex/composer#13]
vagrant@homestead:~/Code$ composer create-project laravel/laravel laravel-shop --prefer-dist "5.5.*"
Installing laravel/laravel (v5.5.28)

  [ErrorException]
  mkdir(): Permission denied

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

请教解决方法。

**Comment by wujingke** [comment]
这个是你权限不对
