### ISSUE TITLE
本地仓库通过nginx 无法转发https请求。导致zip包下载失败。

### ISSUE THREAD

**Issue by AIRootUser** [zencodex/composer#15]
在composer.json 中设置了secure-http:false ， 但还是会
```
Downloading https://dl.laravel-china.org/guzzlehttp/guzzle/407b0cb880ace85c9b63c5f9551db498cb2d50ba.zip
```
nginx无法转发https请求，最后下载失败了。
请问有什么解决方法嘛？ 谢谢！

**Comment by zencodex** [comment]
这个是 http://packagist.laravel-china.org/packages.json 里面的规则。
如果 json 里的规则走 http ，那你的条件是成立的，否则不成立。
