### ISSUE TITLE
ZComposer已经6天没有更新了！

### ISSUE THREAD

**Issue by ZhangChengLin** [zencodex/composer#18]
![QQ截图20190506102725](https://user-images.githubusercontent.com/30773389/57204316-933fb600-6fe9-11e9-94ac-fbcfe465603e.png)

**看图理解题。**

![9150e4e5ly1fm3m796fw9j20h70p0abc](https://user-images.githubusercontent.com/30773389/57204421-51fbd600-6fea-11e9-85a4-699645aa8064.jpg)

**Comment by zencodex** [comment]
谢谢反馈，已经更新了。镜像内容一致再更新，只是这个页面的时间没变，第三方服务的缓存bug。
