### ISSUE TITLE
今天早晨安装包时，提示需要登录，昨天没事

### ISSUE THREAD

**Issue by renakeji** [zencodex/composer#21]
php版本7.1.31

D:\www\company\lxh>composer require jaeger/querylist
Using version ^4.1 for jaeger/querylist
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 17 installs, 0 updates, 0 removals
  - Installing cache/tag-interop (1.0.0): Downloading (0%)    Authentication required (dl.laravel-china.org):
      Username:

**Comment by MADAOCOO** [comment]
我的也是

**Comment by MADAOCOO** [comment]
我这边测试国内服务器不需要登录  但是国外的服务器会提示登录

**Comment by zencodex** [comment]
周末流量暴涨，做了限流，详情请看 https://learnku.com/articles/30254
国外已经禁止加速了，在国外直接使用 官方即可，没必要加速了，目前加速仅限国内。并且每分钟请求有上限。
