### ISSUE TITLE
Installing yiisoft/yii2-bootstrap 这个包怎么也下不下来

### ISSUE THREAD

**Issue by miliPolo** [zencodex/composer#6]
Package operations: 110 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-bootstrap (2.0.8): Downloading (failed)    Failed to download yiisoft/yii2-bootstrap from dist: The "https://files.phpcomposer.com/files/yiisoft/yii2-bootstrap/3f49c47924bb9fa5363c3fc7b073d954168cf438.zip" file could not be downloaded (HTTP/1.1 405 Not Allowed)
    Now trying to download from source

**Comment by zencodex** [comment]
看log 镜像为 phpcomposer 并非是Zcomposer 的镜像，可以根据 README.md 里的提示，安装我们的镜像，并删除 composer.lock

**Comment by miliPolo** [comment]
谢谢，已经解决
