### ISSUE TITLE
大大请教个问题

### ISSUE THREAD

**Issue by MADAOCOO** [zencodex/composer#7]
之前用的中国镜像https://packagist.phpcomposer.com，但是一直有问题！但是我发现在当前项目下改变 镜像地址好像都没有用，只有把composer.lock文件删 了才可以，速度唰唰的，但是问题在于lock删了的话，一些包会被更新的，对于线上环境的话实在是不可取，有没有不用删除lock文件也可使用的方法

**Comment by tinpont** [comment]
```shell
composer update nothing
```
